import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders


def send_report_email(to_email: str, subject: str, report_md: str, pdf_path: str = None):
    """Send research report via Gmail with optional PDF attachment."""

    # Read credentials from .env
    gmail_user     = os.getenv("GMAIL_USER", "")
    gmail_password = os.getenv("GMAIL_APP_PASSWORD", "")

    if not gmail_user or not gmail_password:
        print("[Email] ERROR: GMAIL_USER or GMAIL_APP_PASSWORD not set in .env")
        return False

    # Build email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = gmail_user
    msg["To"]      = to_email

    # Plain text part
    msg.attach(MIMEText(report_md, "plain", "utf-8"))

    # HTML part — convert markdown headings to basic HTML
    html_body = report_md
    import re
    html_body = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^## (.+)$",  r"<h2 style='color:#1a1a2e'>\1</h2>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^# (.+)$",   r"<h1 style='color:#1a1a2e'>\1</h1>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html_body)
    html_body = re.sub(r"^\* (.+)$",  r"<li>\1</li>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"^- (.+)$",   r"<li>\1</li>", html_body, flags=re.MULTILINE)
    html_body = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', html_body)
    html_body = html_body.replace("\n", "<br>")

    full_html = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:800px;margin:auto;padding:20px;color:#222;">
    {html_body}
    <br><hr>
    <p style="color:#999;font-size:11px;">Generated by Autonomous Research Agent</p>
    </body></html>
    """
    msg.attach(MIMEText(full_html, "html", "utf-8"))

    # Attach PDF if exists
    if pdf_path and os.path.exists(pdf_path):
        with open(pdf_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        filename = os.path.basename(pdf_path)
        part.add_header("Content-Disposition", f"attachment; filename={filename}")
        msg.attach(part)
        print(f"[Email] PDF attached: {filename}")

    # Send via Gmail SMTP
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_user, gmail_password)
            server.sendmail(gmail_user, to_email, msg.as_string())
        print(f"[Email] Report sent successfully to {to_email}")
        return True
    except smtplib.SMTPAuthenticationError:
        print("[Email] Authentication failed — check GMAIL_USER and GMAIL_APP_PASSWORD in .env")
        return False
    except Exception as e:
        print(f"[Email] Failed to send: {e}")
        return False